### ISSUE TITLE
souvenir case 

### ISSUE THREAD

**Issue by acarnasss** [mikkokko/csgo_gc#3]
Hello Mikkokko , i wanna thank you for this amazing csgo_gc , but but he has some problem (souvenir case made the game crash , the sticker dont have any color its only grey )

**Comment by mikkokko** [comment]
Hi, thanks for the report. Souvenir unboxing should be fixed by 63fc098cf282c20c28d8becf0bb22abb5e60ca4e. Sticker rarities should've already been fixed by 616cb042ff311c37f45b7a897c2b00f2c7f83275.

**Comment by Laxrt636** [comment]
hey mikkokko i just see the trade up system dont work and only apply to the stattrack skin , thanks for your amazing work btw !
